JS types
tdex-network/tdex-protobuf pull request #78
Opened 2023-03-08 16:53 UTC by sekulicd

This adds JS tags to specific proto message's fields as requested with bellow issue.

This closes issue #76

@altafan please review.

2023-03-08 17:35 UTC, altafan commented on api-spec/protobuf/tdex/v2/swap.proto
> -  uint64 amount_p = 2;
we are missing to add notation also for fee_amount

2023-03-08 17:37 UTC, altafan requested changes
@sekulicd please add notation for `SwapRequest.fee_amount`, then run `make swagger` locally and commit all the changes to update the generated swagger too.

2023-03-08 17:50 UTC, sekulicd commented
> @sekulicd please add notation for `SwapRequest.fee_amount`, then run `make swagger` locally and commit all the changes to update the generated swagger too.

done

2023-03-09 12:26 UTC, altafan approved these changes

2023-03-09 12:27 UTC, merged